# -*- coding: utf-8 -*-
"""Yeni_Satış_Hesaplama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEu4FtZ1J2jLAKHiqZMW2vjYeFiQSnC4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from google.colab import files

# 1. VERİ SETİ (Trend ve mevsimsellik etkisini belirginleştiriyoruz)
dates = pd.date_range(start='2024-01-01', end='2025-12-31')
sales = 100 + (np.arange(len(dates)) * 0.18) + (np.sin(np.arange(len(dates)) * 2 * np.pi / 7) * 30) + np.random.normal(0, 3, len(dates))
df = pd.DataFrame({'Tarih': dates, 'Satis': sales})
df.set_index('Tarih', inplace=True)

# 2. ÖZELLİK MÜHENDİSLİĞİ (Başarıyı artıracak anahtar bölge)
def create_powerful_features(df):
    df = df.copy()
    df['day_of_week'] = df.index.dayofweek
    df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

    # Gecikmeli Özellikler (Lags)
    df['lag_1'] = df['Satis'].shift(1)  # Dünkü satış
    df['lag_7'] = df['Satis'].shift(7)  # Geçen haftaki satış

    # Hareketli İstatistikler
    df['rolling_mean_7'] = df['Satis'].shift(1).rolling(window=7).mean()
    df['rolling_std_7'] = df['Satis'].shift(1).rolling(window=7).std() # Oynaklık bilgisi

    return df

df_final = create_powerful_features(df).dropna()
X = df_final.drop('Satis', axis=1)
y = df_final['Satis']

# 3. MODEL VE EĞİTİM (Daha derin ağaç yapısı)
# 3. MODEL VE EĞİTİM (Bu kısmı aşağıdakiyle güncelle)
model = RandomForestRegressor(
    n_estimators=500,       # Ağaç sayısını artırarak daha kararlı tahminler sağlar
    max_depth=15,           # Modelin derinliğini koruyarak detayları yakalamasını sağlar
    min_samples_split=5,    # Dallanmayı optimize ederek test verisindeki başarıyı (R2) artırır
    random_state=42
)
model.fit(X_train, y_train)
split = int(len(df_final) * 0.8)
X_train, X_test = X.iloc[:split], X.iloc[split:]
y_train, y_test = y.iloc[:split], y.iloc[split:]

# n_estimators ve max_depth değerlerini artırarak öğrenme kapasitesini yükseltiyoruz
model = RandomForestRegressor(n_estimators=300, max_depth=15, min_samples_leaf=2, random_state=42)
model.fit(X_train, y_train)

# 4. TAHMİN VE ANALİZ
predictions = model.predict(X_test)
score = r2_score(y_test, predictions)
print(f"\n🚀 İyileştirilmiş Model Başarı Oranı (R2): {score:.2f}")

# 5. GÖRSELLEŞTİRME
plt.figure(figsize=(14, 7))
plt.plot(y_test.values, label='Gerçek Satış', color='#2ca02c', alpha=0.8)
plt.plot(predictions, label='Tahmin', color='#d62728', linestyle='--')
plt.title(f'Optimize Edilmiş Tahmin Modeli (R2: {score:.2f})')
plt.legend()
plt.show()

# 6. EXCEL DOSYASI VE İNDİRME
export_df = pd.DataFrame({'Tarih': X_test.index, 'Gercek': y_test.values, 'Tahmin': predictions})
export_df.to_excel("Mertcan_Optimize_Satis.xlsx", index=False)
files.download("Mertcan_Optimize_Satis.xlsx")